export const tempBaseData = {
  gadget_name: "Temperature",
  gadget_type: "basicTemp",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
};

export const tempIntData = {
  gadget_name: "Temperature",
  gadget_type: "intermidiateTemp",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
};

export const enBasicData = {
  gadget_name: "Energy",
  gadget_type: "basicEnergy",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  status: 1,
};

export const enIntData = {
  gadget_name: "Energy",
  gadget_type: "intermidiateEnergy",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  status: 1,
};

export const powBasicData = {
  gadget_name: "Power",
  gadget_type: "basicPower",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  status: 1,
};

export const powIntData = {
  gadget_name: "Power",
  gadget_type: "intermidiatePower",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  status: 1,
};

export const humBasicData = {
  gadget_name: "Humidity",
  gadget_type: "basicHumidity",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  status: 1,
};

export const humIntData = {
  gadget_name: "Humidity",
  gadget_type: "intermidiateHumidity",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  status: 1,
};

export const pressBasicData = {
  gadget_name: "Pressure",
  gadget_type: "basicPressure",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  status: 1,
};

export const pressIntData = {
  gadget_name: "Pressure",
  gadget_type: "intermidiatePressure",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  status: 1,
};

export const coBasicData = {
  gadget_name: "Carbon Monoxide (CO)",
  gadget_type: "basicCO",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const coIntData = {
  gadget_name: "Carbon Monoxide (CO)",
  gadget_type: "intermidiateCO",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const co2BasicData = {
  gadget_name: "Carbon Dioxide (CO2)",
  gadget_type: "basicCO2",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const co2IntData = {
  gadget_name: "Carbon Dioxide (CO2)",
  gadget_type: "intermidiateCO2",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const luxBasicData = {
  gadget_name: "LUX Level",
  gadget_type: "basicLux",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const luxIntData = {
  gadget_name: "LUX Level",
  gadget_type: "intermidiateLux",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const noiseBasicData = {
  gadget_name: "Noise",
  gadget_type: "basicNoise",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const noiseIntData = {
  gadget_name: "Noise",
  gadget_type: "intermidiateNoise",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  status: 1,
};

export const vibBasicData = {
  gadget_name: "Vibration",
  gadget_type: "basicVibration",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  min_vibration: 0,
  max_vibration: 50,
  critical_vibration: 100,
  status: 1,
};

export const vibIntData = {
  gadget_name: "Vibration",
  gadget_type: "intermidiateVibration",
  meter_reading: [1, 2, 3, 4, 5],
  timestamp: [1, 2, 3, 4, 5],
  range: "Day",
  meter_name: "Admin Parking",
  node_location: "Pune",
  min_temp: 0,
  max_temp: 50,
  critical_temp: 100,
  min_power: 0,
  max_power: 50,
  critical_power: 100,
  min_energy: 0,
  max_energy: 50,
  critical_energy: 100,
  min_humidity: 0,
  max_humidity: 50,
  critical_humidity: 100,
  min_noise: 0,
  max_noise: 50,
  critical_noise: 100,
  min_co2: 0,
  max_co2: 50,
  critical_co2: 100,
  min_lux: 0,
  max_lux: 50,
  critical_lux: 100,
  min_aud: 0,
  max_aud: 50,
  critical_aud: 100,
  min_pressure: 0,
  max_pressure: 50,
  critical_pressure: 100,
  min_co: 0,
  max_co: 50,
  critical_co: 100,
  min_vibration: 0,
  max_vibration: 50,
  critical_vibration: 100,
  status: 1,
};

export const valve = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicValve",
  gadget_name: "Valve Position",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_valve: 1,
  max_valve: 70,
  critical_valve: 80,
  status: 1,
};

export const valveM = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateValve",
  gadget_name: "Valve Position",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_valve: 1,
  max_valve: 70,
  critical_valve: 80,status : 1
};

export const check = {
  meter_reading: [1, 2, 3, 4, 55],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicCheck",
  gadget_name: "Check In/Out",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_check: 1,
  max_check: 70,
  critical_check: 80,
  status: 1,
};

export const checkM = {
  meter_reading: [1, 2, 3, 4, 55],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateCheck",
  gadget_name: "Check In/Out",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_check: 1,
  max_check: 70,
  critical_check: 80,
  status: 1,
};

export const partcle = {
  meter_reading: [1, 2, 3, 4, 55],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicParticle",
  gadget_name: "Particle",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_particle: 1,
  max_particle: 70,
  critical_particle: 80,
  status: 1,
};

export const partcleM = {
  meter_reading: [1, 2, 3, 4, 55],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateParticle",
  gadget_name: "Particle",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_particle: 1,
  max_particle: 70,
  critical_particle: 80,
  status: 1,
};

export const current = {
  meter_reading: [1, 2, 3, 4, 65],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicCurrent",
  gadget_name: "Current",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_current: 1,
  max_current: 70,
  critical_current: 80,
  status: 1,
};
export const currentM = {
  meter_reading: [1, 2, 3, 4, 65],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateCurrent",
  gadget_name: "Current",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_current: 1,
  max_current: 70,
  critical_current: 80,
  status: 1,
};

export const flow = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicFlow",
  gadget_name: "Flow",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_flow: 1,
  max_flow: 70,
  critical_flow: 80,
  status: 1,
};

export const flowM = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateFlow",
  gadget_name: "Flow",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_flow: 1,
  max_flow: 70,
  critical_flow: 80,
  status: 1,
};

export const alarm = {
  meter_reading: ["NML", "NML"],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicAlarm",
  gadget_name: "Alarm",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_alarm: 1,
  max_alarm: 70,
  critical_alarm: 80,
  status: 1,
};

export const status = {
  meter_reading: ["ON", "ON"],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicSensor",
  gadget_name: "Sensor Status",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_stat: 1,
  max_stat: 70,
  critical_stat: 80,
  status: 1,
};

export const heat = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicHeat",
  gadget_name: "Heat",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_heat: 1,
  max_heat: 70,
  critical_heat: 80,
  status: 1,
};

export const heatM = {
  meter_reading: [1, 2, 3, 4, 75],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateHeat",
  gadget_name: "Heat",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_heat: 1,
  max_heat: 70,
  critical_heat: 80,
  status: 1,
};

export const discomfort = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicDiscomfort",
  gadget_name: "Discomfort",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_heat: 1,
  max_heat: 70,
  critical_heat: 80,
  status: 1,
};

export const discomfortM = {
  meter_reading: [1, 2, 3, 4, 75],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateDiscomfort",
  gadget_name: "Discomfort",
  meter_name: "Garden",
  node_location_jp: "Wing A,Admin Building",
  min_heat: 1,
  max_heat: 70,
  critical_heat: 80,
  status: 1,
};

export const no2 = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicNO2",
  gadget_name: "NO2",
  meter_name: "Garden",
  node_location: "Wing A,Admin Building",
  min_no2: 1,
  max_no2: 70,
  critical_no2: 80,
  status: 1,
};

export const no2M = {
  meter_reading: [1, 2, 3, 4, 75],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateNO2",
  gadget_name: "NO2",
  meter_name: "Garden",
  node_location: "Wing A,Admin Building",
  min_no2: 1,
  max_no2: 70,
  critical_no2: 80,
  status: 1,
};

export const gas = {
  meter_reading: [1, 2, 3, 4, 50],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "basicGas",
  gadget_name: "Gas Detector",
  meter_name: "Garden",
  node_location: "Wing A,Admin Building",
  min_gas: 1,
  max_gas: 70,
  critical_gas: 80,
  status: 1,
};

export const gasM = {
  meter_reading: [1, 2, 3, 4, 75],
  timestamp: [5, 10, 15, 20, 25],
  gadget_type: "intermidiateGas",
  gadget_name: "Gas Detector",
  meter_name: "Garden",
  node_location: "Wing A,Admin Building",
min_gas: 1,
  max_gas: 70,
  critical_gas: 80,
  status: 1,
};
