const nodeInfo = {
  critical_energy: "Critical Energy",
  critical_fuel: "Critical Fuel",
  critical_humidity: "Critical Humidity",
  critical_power: "Critical Power",
  critical_temp: "Critical Temperature",
  energy_watt_hr: "Energy (Watt-Hour)",
  fuel_lt: "Fuel (Liters)",
  humidity_g_m3: "Humidity (g/m³)",
  id: "ID",
  max_energy: "Max Energy",
  max_fuel: "Max Fuel",
  max_humidity: "Max Humidity",
  max_power: "Max Power",
  max_temp: "Max Temperature",
  meter_name: "Meter Name",
  min_energy: "Min Energy",
  min_fuel: "Min Fuel",
  min_humidity: "Min Humidity",
  min_power: "Min Power",
  min_temp: "Min Temperature",
  moisture_g_m3: "Moisture (g/m³)",
  name_of_table: "Table Name",
  node_mac: "Node MAC",
  power_watt: "Power (Watt)",
  temperature_c: "Temperature (°C)",
  timestamp: "Timestamp",
  current_a: "Current (Ampere)",
  co2_p: "CO2 (ppm)",
  aud_db: "Audio (decibal)",
  lux_l: "Illuminance (LUX)",
  pressure_p : "Pressure (Pa)",
  voltage_v: "Voltage (V)",
  valve_position : "Valve Position (%)",
  sensor_status : "Sensor Status (ON/OFF)",
  alarm_status : "Alarm Status (ALM/NML)",
  flow_control : "Flow Control (m3/h)",
  heat_joules : "Heat (mJ/h)",
  vib_mm_s : "Vibration (mm/s)",
  particle : "Particle Monitor",
  min_co2: "Min CO2",
  max_co2: "Max CO2",
  critical_co2: "Critical CO2",
  min_co: "Min CO",
  max_co: "Max CO",
  critical_co: "Critical CO",
  min_lux: "Min Illuminance",
  max_lux: "Max Illuminance",
  critical_lux: "Critical Illuminance",
  min_aud: "Min Audio",
  max_aud: "Max Audio",
  critical_aud: "Critical Audio",
  min_pressure: "Min Pressure",
  max_pressure: "Max Pressure",
  critical_pressure: "Critical Pressure",
  min_current: "Min Current",
  max_current: "Max Current",
  critical_current: "Critical Current",
  min_flow: "Min Flow",
  max_flow: "Max Flow",
  critical_flow: "Critical Flow",
  min_heat: "Min Heat",
  max_heat: "Max Heat",
  critical_heat: "Critical Heat",
  min_vibration: "Min Vibration",
  max_vibration: "Max Vibration",
  critical_vibration: "Critical Vibration",
  min_no2 : "Min NO2",
  max_no2 : "Max NO2",
  critical_no2 : "Critical NO2",
  min_gas : "Min Gas",
  max_gas : "Max Gas",
  critical_gas : "Critical Gas",
  type: "Sensor Type",
};


// const node={
//   english:{
//     const nodeInfo = {
//       critical_energy: "Critical Energy",
//       critical_fuel: "Critical Fuel",
//       critical_humidity: "Critical Humidity",
//       critical_power: "Critical Power",
//       critical_temp: "Critical Temperature",
//       energy_watt_hr: "Energy (Watt-Hour)",
//       fuel_lt: "Fuel (Liters)",
//       humidity_g_m3: "Humidity (g/m³)",
//       id: "ID",
//       max_energy: "Max Energy",
//       max_fuel: "Max Fuel",
//       max_humidity: "Max Humidity",
//       max_power: "Max Power",
//       max_temp: "Max Temperature",
//       meter_name: "Meter Name",
//       min_energy: "Min Energy",
//       min_fuel: "Min Fuel",
//       min_humidity: "Min Humidity",
//       min_power: "Min Power",
//       min_temp: "Min Temperature",
//       moisture_g_m3: "Moisture (g/m³)",
//       name_of_table: "Table Name",
//       node_mac: "Node MAC",
//       power_watt: "Power (Watt)",
//       temperature_c: "Temperature (°C)",
//       timestamp: "Timestamp",
//       current_a: "Current (Ampere)",
//       co2_p: "CO2 (ppm)",
//       aud_db: "Audio (decibal)",
//       lux_l: "Illuminance (LUX)",
//       min_co2: "Min CO2",
//       max_co2: "Max CO2",
//       critical_co2: "Critical CO2",
//       min_lux: "Min Illuminance",
//       max_lux: "Max Illuminance",
//       critical_lux: "Critical Illuminance",
//       type: "Sensor Type",
//     },
//     japanese:{
//       const nodeInfo = {
//         critical_energy: "Critical Energy",
//         critical_fuel: "Critical Fuel",
//         critical_humidity: "Critical Humidity",
//         critical_power: "Critical Power",
//         critical_temp: "Critical Temperature",
//         energy_watt_hr: "Energy (Watt-Hour)",
//         fuel_lt: "Fuel (Liters)",
//         humidity_g_m3: "Humidity (g/m³)",
//         id: "ID",
//         max_energy: "Max Energy",
//         max_fuel: "Max Fuel",
//         max_humidity: "Max Humidity",
//         max_power: "Max Power",
//         max_temp: "Max Temperature",
//         meter_name: "Meter Name",
//         min_energy: "Min Energy",
//         min_fuel: "Min Fuel",
//         min_humidity: "Min Humidity",
//         min_power: "Min Power",
//         min_temp: "Min Temperature",
//         moisture_g_m3: "Moisture (g/m³)",
//         name_of_table: "Table Name",
//         node_mac: "Node MAC",
//         power_watt: "Power (Watt)",
//         temperature_c: "Temperature (°C)",
//         timestamp: "Timestamp",
//         current_a: "Current (Ampere)",
//         co2_p: "CO2 (ppm)",
//         aud_db: "Audio (decibal)",
//         lux_l: "Illuminance (LUX)",
//         min_co2: "Min CO2",
//         max_co2: "Max CO2",
//         critical_co2: "Critical CO2",
//         min_lux: "Min Illuminance",
//         max_lux: "Max Illuminance",
//         critical_lux: "Critical Illuminance",
//         type: "Sensor Type",
//       };
      
//     }    
//   }
// }
export default nodeInfo;
